/** Widths generated by `npm run generate-images` for local files in public/images. */
export const RESPONSIVE_WIDTHS = [640, 960, 1280, 1920] as const;

export type ResponsiveWidth = (typeof RESPONSIVE_WIDTHS)[number];

function splitPath(src: string) {
  const dot = src.lastIndexOf(".");
  if (dot === -1) return null;
  return { base: src.slice(0, dot), ext: src.slice(dot) };
}

export function isLocalRaster(src: string) {
  return src.startsWith("/") && /\.(jpe?g|png|webp)$/i.test(src);
}

export function variantPath(src: string, width: ResponsiveWidth) {
  const parts = splitPath(src);
  if (!parts) return src;
  return `${parts.base}-${width}w${parts.ext}`;
}

export function buildSrcSet(src: string): string | undefined {
  if (isLocalRaster(src)) {
    return RESPONSIVE_WIDTHS.map((width) => `${variantPath(src, width)} ${width}w`).join(", ");
  }

  if (src.includes("images.unsplash.com")) {
    const base = src.split("?")[0];
    return RESPONSIVE_WIDTHS.map(
      (width) => `${base}?auto=format&fit=crop&w=${width}&q=88 ${width}w`,
    ).join(", ");
  }

  return undefined;
}

export function defaultResponsiveSrc(src: string, preferred: ResponsiveWidth = 1280) {
  if (isLocalRaster(src)) {
    return variantPath(src, preferred);
  }

  if (src.includes("images.unsplash.com")) {
    const base = src.split("?")[0];
    return `${base}?auto=format&fit=crop&w=${preferred}&q=88`;
  }

  return src;
}
