import {
  LegalContactListItem,
  legalContactListClassName,
} from "@/components/legal/LegalContactIcons";

export function EngagementTermsBody() {
  return (
    <div className="min-w-0 break-words">
      <p className="min-w-0 break-words">
        <strong>Draft notice:</strong> This page is website draft copy pending formal legal review.
        It sets out standard terms of engagement for reference only and does not replace a signed
        engagement letter or contract.
      </p>
      <p className="min-w-0 break-words">
        <strong>Editorial review needed:</strong> The source document includes placeholder tokens and
        typographical items for legal confirmation, including{" "}
        <code className="text-pelagic-charcoal">[S1.1]</code>,{" "}
        <code className="text-pelagic-charcoal">[S2.1]</code>,{" "}
        <code className="text-pelagic-charcoal">[S3.1]</code>, &quot;Theis&quot;, &quot;Tthe&quot;,
        &quot;15 30 days&quot;, sub-clause labels &quot;(de)&quot; / &quot;(fe)&quot;, &quot;bythrough&quot;,
        and duplicated words such as &quot;the the&quot; and &quot;all any&quot;.
      </p>
      <p className="min-w-0 break-words font-semibold text-pelagic-charcoal">
        Pelagic Marine Solutions LLC
      </p>
      <p className="min-w-0 break-words font-semibold text-pelagic-charcoal">
        STANDARD TERMS AND CONDITIONS OF ENGAGEMENT
      </p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">1. Interpretation</h2>
      <p className="min-w-0 break-words">In these Conditions, the following definitions apply:</p>
      <dl className="min-w-0 space-y-3 break-words">
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Agreement”</dt>
        <dd className="min-w-0 break-words pb-2">means the agreement between the Company and the Client for the provision of Services in accordance with the Engagement Letter and these Conditions.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Client”</dt>
        <dd className="min-w-0 break-words pb-2">means the person, company, firm, organisation or other legal entity, as identified in the Engagement Letter, which has requested the Company to provide Services.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Client Group”</dt>
        <dd className="min-w-0 break-words pb-2">means the Client, its affiliates, subsidiaries or holding company from time to time, and their respective officers, representatives, employees, agents, consultants and subcontractors. “Subsidiary” and “holding company” shall have their generally accepted meanings.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Company”</dt>
        <dd className="min-w-0 break-words pb-2">means Pelagic Marine Solutions LLC, having its office at Office No. 104, Almas Business Center, Aghaadir Building, Al Raffa, Dubai, U.A.E.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Company Group”</dt>
        <dd className="min-w-0 break-words pb-2">means the Company, its affiliates, subsidiaries or holding company and their respective officers, representatives, employees, agents, consultants and subcontractors thereto.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Conditions”</dt>
        <dd className="min-w-0 break-words pb-2">means these Terms and Conditions as may be amended from time to time.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Consequential Loss”</dt>
        <dd className="min-w-0 break-words pb-2">means (i) any and all consequential or indirect loss under U.A.E. law and (ii) any or all loss and/or deferral of production, loss of revenue, profit or anticipated profit (if any), loss of use, or loss of product, whether direct or indirect and whether or not foreseeable.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Compass Deviation Card”</dt>
        <dd className="min-w-0 break-words pb-2">means a card or similar document with compass roses printed on it concentrically, recording the deviation to be applied on a given heading during a given voyage, for which the navigator must compensate when using the ship’s magnetic compass to steer a course.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Deliverables”</dt>
        <dd className="min-w-0 break-words pb-2">means any reports, certificates, assessments, calculations, analyses, drawings, designs, opinions, recommendations, advice or other documents or materials prepared or issued by the Company in connection with the Services.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Engagement Letter”</dt>
        <dd className="min-w-0 break-words pb-2">means the Company’s letter or  other written document or communication including any proposal, quotation, email issued by the Company and  accepted or agreed by the Client, describing the Services to be performed and the terms under which such Services are being provided.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Fee or Fees”</dt>
        <dd className="min-w-0 break-words pb-2">means the amount payable by the Client as remuneration for the Services provided by the Company.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Pre-purchase Survey”</dt>
        <dd className="min-w-0 break-words pb-2">means a vessel inspection and/or survey conducted pursuant to which a report is produced by the Company which is to be used, or relied upon, in order to make a decision on, or to provide money for, the purchase of any vessel. The survey does not include any valuation of the vessel.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Services”</dt>
        <dd className="min-w-0 break-words pb-2">means the services or work to be performed or provided or supplied by the Company to the Client as set out in the Engagement Letter or otherwise agreed or confirmed in writing between the Company and the Client, including any Deliverables prepared or issued in connection therewith.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Third Party”</dt>
        <dd className="min-w-0 break-words pb-2">means any person, company, firm, organisation or other legal entity which is not a member of either the Company Group or the Client Group.</dd>
        <dt className="min-w-0 break-words font-semibold text-pelagic-charcoal">“Warranty Survey”</dt>
        <dd className="min-w-0 break-words pb-2">means any service where the Company, in the course of the Services, conducts an evaluation of operational risks relating to any shipyard, vessel or other project by performing technical reviews and on-site inspections and provides a report and/or certificate(s) containing recommendations and attesting that the assured has complied with the warranty imposed by the Client and/or policy to which the project relates.</dd>
      </dl>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">2. Basis of Contract</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">2.1</strong> Theis Agreement constitutes the entire agreement between the parties. The Client acknowledges that it has not relied on any statement, promise or representation made or given by or on behalf of the Company that is not set out in this Agreement.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">2.2</strong> These Conditions apply to the Agreement to the exclusion of any other terms that the Client seeks to impose or incorporate (including its own terms and conditions) or which are or may be implied by statute, trade, custom, practice or course of dealing.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">2.3</strong> Unless otherwise agreed in writing between the Parties, these Conditions shall also apply to any other services of whatever nature as may be provided by the Company to the Client.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">2.4</strong> The Agreement shall take effect on the earliest of the following events: (i) when the Client provides written confirmation of the instruction in the Engagement Letter or acceptance mail, accepting the agreed scope of work and these Terms and Conditions; or (ii) when the performance of the work has commenced by the Company, unless the Client objects to these Terms and Conditions within 48 hours of the Company starting to perform the Services.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">2.5</strong> The Company shall have the right to refuse to commence the Services until such Engagement Letter has been signed by the Client.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">2.6</strong> The Engagement Letter, these Conditions and any applicable scope of work, assumptions, qualifications or limitations expressly identified by the Company shall together constitute the Agreement governing the Services. In the event of any inconsistency, the Engagement Letter shall prevail to the extent of such inconsistency, unless expressly stated otherwise.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">3. Provision of Services by the Company</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.1</strong> The Company shall use reasonable care, diligence and skill in performing the Services.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.2</strong> The Company shall use reasonable endeavours to meet any performance dates that may be specified, but any such dates shall be treated as estimates and time shall not be considered to be of the essence for performance of any Services.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.3</strong> The Services to be provided by the Company shall be as described in the Engagement Letter and/or set out within insurers’ policies or specific survey criteria for the particular survey/service being provided by the Company. The Company shall not be responsible for matters falling outside the agreed scope of the Services unless expressly agreed in writing. The Company has the right to make any changes to the Services which are necessary to comply with any applicable law or safety requirements or which do not materially affect the nature or quality of the Services being provided.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.4</strong> The Services are provided by the Company to the Client on an exclusive basis for the purpose and scope specified in the Engagement Letter. Unless otherwise agreed in writing in the Engagement Letter, the Company shall have no liability or responsibility to any Third Party in connection with the provision of the Services or any reliance placed upon any Deliverable by such Third Party. Any report, certificate, calculation, analysis, recommendation or other deliverable is prepared solely for the Client and for the specific purpose stated in the Engagement Letter based upon the information, documents, drawings, specifications, data and other materials made available to the Company, together with the observations made by the Company in the course of performing the Services. It may not be relied upon by any Third Party without the Company’s prior written consent. The Client shall not circulate, publish or make any such deliverable available to any Third Party without such consent and without ensuring that the Third Party is bound by terms no less protective of the Company than these Conditions.</p>
      <p className="min-w-0 break-words">Any permitted recipient or user of a Deliverable shall read it as a whole together with all assumptions, qualifications, limitations and recommendations contained therein and, where applicable, together with these Conditions. No part of a Deliverable may be taken out of context or relied upon separately from the Deliverable as a whole.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.5</strong> Where Services are to be provided or performed by the Company in a foreign jurisdiction or are related to property found in such jurisdictions, the Client shall obtain any and all necessary governmental and regulatory consents and approvals required to enable the Company to provide or perform the Services. The Company shall be under no obligation to provide any Services until such time as the Client has obtained any necessary consents and approvals.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.6</strong> In the performance of the Services, neither the Company nor any member of the Company Group shall be required to contravene or breach any sanction, prohibition or regulation imposed by any national, supranational or international government organisation or body.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.7</strong> Any assessment in respect of a warranty or pre-purchase survey will be made solely on the basis of the information provided to the Company, the documents examined and the observations of the surveyor at the time of attendance(s) at the shipyard, site or onboard the vessel. The Company shall be entitled to rely, without independent verification, upon all information, drawings, data, documents, representations and instructions provided by the Client or any Third Party designated by the Client. The Company shall have no liability for any error, omission, inaccuracy or incompleteness in such information, or for any consequence arising therefrom. Where complete information is unavailable, the Company may make reasonable assumptions based on the information available to it, professional judgment and generally accepted industry practice and where reasonably practicable, be stated in the relevant Deliverable or report. The Client remains solely responsible for the accuracy and completeness of all information supplied and for the consequences of any assumptions that prove incorrect. The Company shall not be liable for any error, omission or inaccuracy in a Deliverable to the extent arising from inaccurate, incomplete, misleading or withheld information supplied by the Client or any Third Party, or from assumptions reasonably made as a consequence of incomplete information.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.8</strong> In respect of insurance damage related assessments, the Company shall submit interim report advices, a final report and an addendum report to the Client during and following completion of the agreed Services, describing the findings and assessments of all surveys and inspections relating to the purpose of the Client’s instruction, unless otherwise expressly instructed by the Client not to do so. The Company shall endeavour to submit its reports, results and related Services to the Client within reasonable agreed timescales. Where such timescales are agreed in writing, the Client accepts that such timescales are necessarily an estimate only and are not guaranteed unless expressly stated in writing as such.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.9</strong> With respect to marine warranty work, the surveyor’s recommendations are to be complied with fully and within the allocated time period, otherwise the insurer’s warranty will be deemed null and void.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">3.10</strong> Unless expressly agreed otherwise in writing, any inspection, survey or assessment undertaken by the Company is limited to the agreed scope of Services and to those areas, systems, equipment, documents and conditions that are reasonably accessible or capable of assessment at the relevant time. The Company shall not be responsible for latent or concealed defects, conditions that could not reasonably have been identified within the agreed scope, or any subsequent change in the condition, operation or circumstances of the vessel, equipment, site or subject matter following completion of the relevant Services.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">4. Client’s Obligations</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">4.1</strong> The Client shall: (a) provide the Company with complete and accurate information and materials including, where applicable, drawings, plans, specifications, records and technical data as the Company may reasonably require and in sufficient time to enable the Company to provide or perform the Services in an efficient and effective manner and promptly notify the Company of any material change, error or omission in any information previously supplied; (b) co-operate with the Company in all matters relating to the provision or performance of the Services; (c) provide the Company with safe access to the Client’s premises, office accommodation, vessels, installations and other facilities as may reasonably be required in the performance of the Services; and (d) comply with its payment obligations as set out in Clause 5.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">4.2</strong> If the provision of Services by the Company is prevented or delayed by any act, omission or failure by the Client in the performance of its obligations, the Company shall be entitled to suspend or delay performance of the Services until such time as the act, omission or failure by the Client has been remedied to the satisfaction of the Company.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">4.3</strong> All interpretations, research, analysis, recommendations, advice or interpretational data furnished by the Company are opinions and are an advisory only. The Client assumes full responsibility for the use of such opinions and for all resulting decisions, and the Company shall not be liable for any claims arising out of such use by the Client. Final operational, navigational, commercial, safety and other decisions remain the sole responsibility of the vessel owner, operator, master, charterer or other relevant stakeholders or other person having operational control or responsibility. The Company accepts no responsibility for any operational and commercial decisions made or action taken (or not taken) by the Client or any Third Party on the basis of the Services provided by the Company. This limitation expressly applies to claims of third parties relying on the Company’s interpretations, research, analysis, recommendations, advice or interpretational data.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">4.4</strong> The Client undertakes to name the Company as a co-assured under any insurance policy effected by the Client or any other party which is relevant to the scope of work, and will provide to the Company, on demand, details of the cover provided therein. Such insurance shall be deemed primary and first to react ahead of any insurance covering the same risks maintained by the Company. The Client agrees that the Company’s total liability to the Client under the Agreement shall not exceed US$100,000 (one hundred [S1.1]thousand United States Dollars), and the Client undertakes to procure that its insurers waive all rights of subrogation against the Company and/or Pelagic Marine Solutions LLC.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">4.5</strong> If the Client becomes aware of any claim or circumstances which might involve litigation or arbitration concerned or connected with the subject matter of the Agreement, the Client shall inform the Company immediately.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">4.6</strong> The Client shall indemnify the Company for any loss, liability, cost or expense arising directly or indirectly by reason of a default on the part of the Client in fulfilling its obligations under this Agreement.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">5. Fees</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.1</strong> The Fee due and payable by the Client to the Company shall be calculated in accordance with the terms set out in the Engagement Letter.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.2</strong> The Company is entitled to charge the Client for any expenses reasonably incurred in the performance of the Services including, but not limited to, travelling expenses, accommodation costs and any other reasonable incidental expenses on an actual cost basis unless otherwise agreed in the Engagement Letter. The Client shall reimburse the Company for the cost of any services provided by Third Parties who may be instructed by the Company, with the prior approval of the Client, to assist in the performance of the Services.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.3</strong> Should the Company be required to provide services in addition to those specified in the Engagement Letter, the Client shall pay a supplemental fee for such additional services in accordance with the Company’s standard hourly rates or such other rate or fee as may be agreed between the Parties. So far as is reasonably possible, any additional services and fees shall be agreed in writing in advance of such additional services being carried out.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.4</strong> Unless otherwise stated in the Engagement Letter, the Company shall invoice the Fee to the Client on a monthly basis. The Client shall pay the amounts invoiced without deduction or set-off within 30 days from the date of the invoice unless agreed otherwise in the Engagement Letter.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.5</strong> The Company reserves the right to request funds on account from the Client in respect of any anticipated expenses, Third Party services and/or Fees. Such funds will be held on account until the completion of the Services and will be drawn down upon to settle any outstanding Fees and/or Third Party costs/expenses incurred on behalf of the Client. Any excess funds on account will thereafter be returned to the Client at the conclusion of the Services. If there are insufficient funds on account to meet the Fees and/or Third Party services/expenses, payment of any balance shall fall due in accordance with Clause 5.4 above.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.6</strong> Fees charged by the Company are exclusive of amounts in respect of value added tax (VAT) or similar applicable sales taxes. Where any taxable supply for VAT purposes is made under this Agreement, the Client shall, on receipt of a valid VAT invoice, pay to the Company such additional amounts in respect of VAT as are chargeable on the supply of the Services at the same time as payment is due for the supply of the Services.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.7</strong> The Client is responsible for the payment of all other taxes (excluding any taxes on profits or corporation tax chargeable on the Fees received by the Company), including but not limited to withholding taxes, service taxes, duties and other fiscal charges which may be levied or become due in respect of the Fees.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.8</strong> The Client shall pay all amounts due under the Agreement in full without any deduction or withholding. The Client is not entitled to assert any credit, set-off or counterclaim against the Company in order to justify withholding payment of any amount due in whole or in part. Should any amounts be required by law to be deducted or withheld from any amount due under this Agreement, the Client shall pay to the Company an amount such that the net amount received by the Company would be the same as if no such withholding or deduction had taken place.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.9</strong> Any failure by the Client to make payment in full by the due date shall entitle the Company to charge interest on the overdue amount at a fixed rate of five per cent (5%) per [S2.1]annum, accruing on a daily basis from the due date until the date of payment, compounded quarterly.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.10</strong> Any failure on the part of the Client to make payment of an invoice shall entitle the Company, without prejudice to any other rights it may have, to suspend the performance of the Services until such time as payment has been made in full including the payment of any interest due.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.11</strong> If any part of an invoice is genuinely in dispute, the Client shall notify the Company immediately upon receipt of the invoice as to any part of the invoice which is in dispute, giving full reasons as to why a portion of the invoice is disputed, and shall nevertheless pay the undisputed part within 30 days of the invoice date. The parties shall endeavour to resolve the disputed portion without delay.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">5.12</strong> Without prejudice to any rights of recovery which the Company might have against a third party, the Company shall treat the Client as the person responsible for paying for the Services. The Company shall not need to be concerned as to whether the Client considers itself to be principal or acting as agent only, nor whether the Client is, or is not, paid by a third party.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">6. Amendment and Variation</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">6.1</strong> Except as otherwise provided, any amendment or variation, including the introduction of any additional terms and conditions, to the Agreement shall only be binding when agreed in writing and signed by the Company.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">6.2</strong> Any additional costs, expenses or fees which may be incurred by the Company in connection with an amendment or variation of the Agreement shall be borne by the Client. Notwithstanding any prior agreement between the Parties as to a fixed Fee, the Company may make the necessary adjustments to the Fee should it become aware of the inaccuracy of any information provided to it by the Client or if the assumptions contained in the Engagement Letter are incorrect.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">6.3</strong> In the event that it becomes necessary for the Company to amend or vary the arrangements relating to the provision and performance of the Services due to circumstances outside its control, the Company shall notify the Client as soon as possible. The Company shall endeavour to keep any amendments or variations to a minimum and shall endeavour to offer the Client alternatives which are as close to the original arrangements as can be reasonably expected under the circumstances.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">7. Indemnities</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">7.1</strong> The Company Group shall be responsible for and shall save, indemnify, defend and hold harmless the Client Group from and against all claims, losses, damages, costs, expenses and liabilities in respect of: (a) loss or damage to property of the Company Group, whether owned, hired, leased or otherwise provided by the Company Group, arising from, relating to or in connection with the performance or non-performance of the Agreement; (b) personal injury, including death or disease, to any person employed by or subcontracted by the Company Group arising from, relating to or in connection with the performance or non-performance of the Agreement.; and (c) any Consequential Loss which may be incurred by a member of the Company Group .</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">7.2</strong> The Client Group shall be responsible for and shall save, indemnify, defend and hold harmless the Company Group from and against all claims, losses, damages, costs, expenses and liabilities in respect of:</p>
      <ul className="min-w-0 list-[lower-alpha] break-words pl-5 sm:pl-6">
        <li className="min-w-0 break-words">(a) loss or damage to property of the Client Group or any Third Party arising from, relating to or in connection with the performance or non-performance of the Agreement; (b) any incident of pollution or contamination, and the control and removal thereof, arising from, relating to or in connection with the performance or non-performance of the Agreement as caused by any member of the Client Group and/or any Third Party or emanating from any property of the Client Group or a Third Party;</li>
        <li className="min-w-0 break-words">(c) the reliance on and use of any information or reports provided to the Client by the Company by any Third Party any unauthorised disclosure, distribution, reliance on or use by any Third Party of any information, report or other Deliverable provided by the Company to the Client, where such information, report or Deliverable has been disclosed or made available to such Third Party by or on behalf of the Client without the Company’s prior written consent;which has been provided with a copy of such information or reports by any member of the Client Group;</li>
        <li className="min-w-0 break-words">(d) any claim by a Third Party arising from or in connection with  unauthorised reliance on or use of any report, certificate, calculation, analysis, recommendation or other Deliverable of the Company;</li>
        <li className="min-w-0 break-words">(de) personal injury, including death or disease, to any person employed by the Client Group or any Third Party arising from, relating to or in connection with the performance or non-performance of the Agreement; and (fe) any Consequential Loss which may be incurred by a member of the Client Group or any Third Party.</li>
      </ul>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">7.3</strong> The exclusions and indemnities provided for in Clauses 7.1 and 7.2 above shall apply irrespective of the cause and regardless of whether it was due to the negligence or breach of duty (statutory or otherwise) of the indemnified party or any other party. The exclusions and indemnities shall apply regardless of any contractual, tortious or other claim under law.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">7.4</strong> Any proceedings against the Company in respect of any and all claims arising out of or in connection with this Agreement and the Services performed by the Company, whether contractual, tortious (including negligence), breach of statutory duty or otherwise, shall be commenced within 12 months of the completion of the Services or the submission date of the Company’s report or invoice to the Client, whichever is the earlier. If no such proceedings are commenced within 12 months as aforesaid, then the Company shall be discharged and released from any liability in respect of any claims the Client may have against the Company.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">7.5</strong> Except where expressly stated in the Engagement Letter, the Company does not warrant or guarantee any particular result, outcome, condition, performance, seaworthiness, fitness for purpose or suitability arising from the Services or any Deliverable The Company gives no warranty, express or implied, as to the fitness for purpose or suitability of the Services or results, and the Client waives any terms, conditions or warranties otherwise incorporated or implied by law to the fullest extent permitted by law. There can be no guarantee that errors or irregularities, if present at the shipyard, will be detected by the Company in the course of performing a shipyard assessment. Similarly, a pre-purchase survey does not warrant the seaworthiness of the vessel but attests to the vessel’s condition at the time of the survey. The prospective buyer of the vessel should independently satisfy itself including themselves bythrough any  further inspection/examination it considers necessary and review of the vessel’s class records. The Company does not warrant that all defects, irregularities or non-conformities will be detected.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">8. Limitation of Liability</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.1</strong> The Company shall bear no liability to the Client Group under the Agreement, whether contractual, tortious (including negligence), breach of statutory duty or otherwise, for the supply of the Services, save where the Company has failed to perform the Services with the necessary reasonable care, diligence and skill and then only subject to the exclusions, limitations and liability cap set out in this Agreement.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.2</strong> In no circumstances will the Company be liable to the Client, the Client Group or any third party for any consequential or indirect incidental, special or punitive  loss, damage or expense including loss of profit, revenue, use, production, business, opportunity, contract or anticipated savings, whether direct or indirect and whether or not foreseeable. The Client agrees to release, indemnify and hold harmless the Company from and against any and all claims, demands, lawsuits or actions for damages, including legal fees, for harm or loss to persons and/or property, tangible, intangible or otherwise, which may be brought against the Company, incidental to, arising out of or in connection with the performance of the scope of work.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.3</strong> In relation to Clause 3.7, should any of the equipment, machinery or products contain latent defect(s) which were not apparent at the time the survey or valuation was conducted and could not reasonably have been expected to have been discovered by such survey, the Company shall bear no liability whatsoever in respect of such defects.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.4</strong> The Company does not warrant in any way whatsoever the purpose or suitability of the Services and, to the extent permitted by law, the Client Group waives any terms, conditions or warranties (either express or implied) as may otherwise be incorporated into this Agreement by law.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.5</strong> Save as provided for in Clause 7.1, the Client accepts that, in view of the large amounts that may be at risk related to the locations, facilities and work involved, the Company cannot be expected to purchase professional indemnity insurance for the full amount of any such risk, and the Client acknowledges in all circumstances that it is reasonable for the Company to arrange professional indemnity cover up to an amount of US$100,000 (the [S3.1]“Indemnity Limit”). To the maximum extent permitted by the laws of the United Arab Emirates,  Tthe Company’s total liability in contract, tort (including negligence or breach of statutory duty or strict liability, including but not limited to unseaworthiness, product liability or vicarious liability), misrepresentation, under statute, or otherwise arising in connection with the performance or contemplated performance of the contract shall not exceed the Indemnity Limit. The Client agrees that in no circumstances can the Company be liable for any greater amount. The Company agrees to maintain professional indemnity cover for an amount at least equal to the Indemnity Limit and to advise the Client forthwith if it becomes unable to obtain or maintain professional indemnity insurance for any reason. Nothing in these Conditions shall exclude or limit the Company’s liability for fraud, wilful misconduct, or for death or personal injury caused by its negligence to the extent that such exclusion or limitation is prohibited by UAE law.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.6</strong> No representative of the Company shall bear any personal legal liability to the Client, whether contractual, tortious (including negligence), breach of statutory duty or otherwise.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.7</strong> In the event that the Company is held liable to the Client under the Agreement and a Third Party is also held liable in respect of the same claim, the Company shall only bear liability to the extent that such loss is attributable to the Company. The Client’s failure or inability to recover its loss from the Third Party shall not increase the Company’s liability hereunder.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">8.8</strong> While the Company shall exercise the reasonable care, diligence and skill required under Clause 3.1, the Client acknowledges that professional assessments, calculations, analyses and recommendations may involve professional judgment and may be subject to limitations arising from the information, access and conditions available at the relevant time. The Company does not warrant that any Deliverable will be entirely free from inadvertent errors or omissions. Where the Company becomes aware of a material error or omission in a Deliverable, it shall be entitled, where reasonably practicable, to correct, supplement or reissue the relevant Deliverable.</p>
      <p className="min-w-0 break-words">Nothing in this Agreement excludes or limits any liability of the Company that cannot be excluded or limited under applicable law.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">9. Preparation of Site</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">9.1</strong> In the event that the Services to be supplied by the Company to the Client include physical work to be carried out on premises or locations owned by the Client or under its access or control (the “Site”), any costs or expenses incurred in relation to the preparation of the Site shall be for the account of the Client.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">9.2</strong> The Client shall be deemed to have legal and operational control over the Site for the duration that the work is to be carried out by the Company. The Company shall not have or be deemed to have any legal or operational control over the Site, and any of its officers, representatives, employees, agents, consultants and subcontractors who may be present at the Site shall be there only in an advisory capacity. Should the presence of the Company’s personnel be required onboard any mobile offshore drilling unit or other vessel owned, chartered or operated by the Client or any member of the Client Group (the “Unit”), legal and operational control over the Unit shall be deemed to be held by the Client at all times.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">9.3</strong> The Client shall procure that the Company has unobstructed and continued access to the Site in order to carry out the Services and shall make any necessary arrangements and procure any necessary facilities in order to enable the Services to be performed.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">9.4</strong> The Client shall make all arrangements and take all security measures to ensure that the Site is safe. The Client shall also carry out a safety briefing for the Company’s personnel and shall ensure that it is in compliance with all safety regulations, whether legal, statutory or otherwise.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">9.5</strong> In the event that the scope of the Services calls for any rig movement, tow master or mooring master activity to be carried out, this shall be deemed to have ended upon the final positioning or berthing of the Unit at the place specified in the Engagement Letter, unless otherwise expressly agreed between the Parties. Any pre-loading operations shall be performed exclusively by the Client, owner or operator of the Unit, as the case may be.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">10. Intellectual Property Rights</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">10.1</strong> All intellectual property rights in or arising out of or in connection with the Services shall be owned by the Company, and no right to, interest in or licence to any intellectual property rights owned by the Company shall be granted to the Client, save as expressly set out below.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">10.2</strong> Intellectual property rights that are the property of each Party prior to the date of this Agreement, or developed outside the scope of this Agreement, shall remain the sole property of that Party.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">10.3</strong> For any intellectual property rights created in the course of the provision or performance of the Services that are the property of the Company, the Company grants to the Client a non-exclusive and non-transferable royalty-free licence to use said intellectual property rights solely for the purpose for which the relevant Services and Deliverables were commissioned, provided that any Fees invoiced by the Company have been paid by the Client in full. The Client shall not reproduce, modify, publish, distribute, commercially exploit or permit any Third Party to rely upon any Deliverable except with the Company’s prior written consent or as expressly permitted under the Agreement.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">11. Insurance</h2>
      <p className="min-w-0 break-words">Both Parties shall each maintain adequate and appropriate insurance cover for the liabilities arising out of or in connection with this Agreement. Any rights of subrogation which may be exercised by the Parties’ respective underwriters shall be waived to the extent of any indemnities granted pursuant to Clause 7 of this Agreement.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">12. Confidentiality</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">12.1</strong> Both Parties shall keep in strict confidence all technical or commercial know-how, specifications, inventions, processes, business secrets or initiatives which are of a confidential nature and have been disclosed to them by the other Party, and any other confidential information concerning the other Party’s business, products or services.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">12.2</strong> Neither Party shall use the other Party’s confidential information for any purpose other than to perform its obligations under the Agreement, unless express permission has been obtained or where required to do so by reason of any legal or statutory purpose or by order of a court of law.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">12.3</strong> Both Parties shall restrict disclosure of confidential information to such of their representatives, employees, agents, consultants and subcontractors as need to know it for the purpose of discharging the Party’s obligations under the Agreement, and shall ensure that such persons are subject to obligations of confidentiality corresponding to those which bind the Party receiving the confidential information.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">12.4</strong> This Clause shall survive termination of the Agreement, and each Party undertakes that it shall not, for a period of five (5) years after termination of the Agreement, disclose to any person any confidential information pertaining to the other Party except as permitted under Clause 12.2.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">13. Termination</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">13.1</strong> Without in any way limiting its other rights and remedies, either Party may terminate the Agreement upon giving written notice to the other Party if: (a) the other Party commits a material breach of the Agreement and (if such breach is remediable) fails to remedy that breach within 15 30 days of being notified in writing of that breach and required to remedy it; (b) the other Party suspends, or threatens to suspend, payment of its debts, is unable to pay its debts as they fall due, or admits inability to pay its debts; (c) the other Party (being a company) is subject to any step or proceeding in connection with its winding up, administration, receivership or insolvency, or (being an individual) is subject to a bankruptcy petition or order; or (d) any event occurs, or proceeding is taken, with respect to the other Party in any jurisdiction to which it is subject that has an effect equivalent or similar to any of the events mentioned in this Clause 13.1.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">13.2</strong> The Company shall be entitled to terminate the Agreement should any circumstances arise which are beyond the reasonable control of the Company or which, in the Company’s reasonable opinion, make the continued performance of the Services unlawful, unsafe or impracticable, and which necessitate the termination of this Agreement.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">13.3</strong> The Company shall be entitled to terminate the Agreement by giving 14 days’ written notice of intention if the Client does not provide the necessary technical data, drawings or other information or cooperation, access, approvals or instructions reasonably required by the Company needed to carry out the agreed Services or, with reference to Clause 5.3, if the Client does not issue further/additional written instructions in respect of other services requested that have not been identified within the original Engagement Letter or otherwise agreed in writing between the Company and the Client.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">13.4</strong> The Company shall be entitled to terminate the Agreement if the Client becomes involved, or is likely to become involved, in giving any evidence in any litigation or arbitration proceedings affecting the subject matter of the agreed terms and conditions in respect of the performance of the Services, or any matter connected with or arising from the Agreement, which would result in or in the Company’s reasonable opinion is likely to result in a conflict of interest between the Company and the Client.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">13.5</strong> Without limiting its other rights or remedies, the Company may terminate the Agreement with immediate effect by giving written notice to the Client if the Client fails to pay any amount when due under the Agreement.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">13.6</strong> On termination of the Agreement for any reason: (a) the Client shall immediately pay to the Company all of the Company’s outstanding unpaid invoices and interest thereon if due and, in respect of Services supplied up to the date of termination but for which no invoice has been submitted, the Company shall submit an invoice which shall be payable by the Client immediately on receipt, together with all any additional reasonable costs expenses,incurred by the Company in connection with the Services or as a result of the the early termination; (b) the Company shall be entitled to retain any advance payment or deposit made by the Client in respect of the Fees; (c) the accrued rights, remedies, obligations and liabilities of the Parties as at expiry or termination shall not be affected; and (d) clauses which expressly or by implication have effect after termination shall continue in full force and effect.</p>
      <p className="min-w-0 break-words">The Company may terminate the Agreement with immediate effect by written notice where the Company reasonably determines that continuing the Agreement or providing the Services may cause the Company to breach any applicable law, sanctions, export control, anti-bribery, anti-money laundering or other regulatory requirement.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">14. Suspension of Agreement</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">14.1</strong> Should the Agreement be suspended due to any breach on the part of the Client, an event of Force Majeure, or any other reason attributable to the Client, the Client shall reimburse the Company for: (a) any and all costs and expenses incurred by the Company in dismissing (and re-hiring, if necessary) any employees hired specifically for the purpose of this Agreement; (b) any and all costs and expenses incurred by subcontractors under any subcontract entered into in furtherance of this Agreement; (c) any and all other costs and expenses incurred by the Company in respect of the period of suspension; and (d) loss of the Company’s anticipated profits under this Agreement for the period of suspension.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">14.2</strong> The Company shall have the right (but shall not be obliged) to give notice of termination of the Agreement in the event any such period of suspension continues for a period of more than 7 days.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">15. General</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">15.1</strong> Duration of Work / Timeline. The Company will make every reasonable effort to adhere to the proposed timelines for completion of the engineering assessment as outlined in the work scope. However, due to the nature of the work, which involves detailed technical evaluations and assessments, the timeline may be subject to change based on the complexity and findings that arise during the assessment process. The Company expressly disclaims any liability for delays in completion of the assessment arising from circumstances outside the Company’s reasonable control, delays or failures by the Client or Third Parties, changes in scope, incomplete or inaccurate information, restricted access, or circumstances identified during the Services requiring further investigation, including but not limited to any consequential, incidental or indirect damages or losses that may result from such delays. By accepting the proposal, the Client acknowledges and agrees that the Company shall not be held liable for any costs, expenses or liabilities incurred as a result of delays, irrespective of the cause of such delays.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">15.2</strong> Assignment and Subcontracting. Neither Party shall, without the prior written consent of the other (such consent not to be unreasonably withheld), assign or transfer any of its rights or obligations under the Agreement. The Company shall be entitled to subcontract its obligations under the Agreement to a reputable subcontractor and, where possible, shall notify the Client prior to the appointment.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">15.3</strong> Notices. Any notice or other communication required to be given under or in connection with this Agreement shall be in writing and shall be delivered to the other Party by hand, sent by email, or sent by recorded delivery to the registered address set out in the Engagement Letter. Any notice shall be deemed duly received if delivered personally, when left at the address referred to above; if sent by recorded delivery, at 9 a.m. on the second business day after posting; or if sent by email, on the next business day after transmission.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">15.4</strong> Waiver. A waiver of any right under the Agreement by the Company shall only apply to the specific matter of which it is the subject, shall only be effective if in writing, and shall not be deemed a waiver of any subsequent breach or default on the part of the Client. No failure or delay by the Company in exercising any right or remedy under the Agreement or by law shall constitute a waiver of that or any other right or remedy.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">15.5</strong> Severance. If a court or any other competent authority finds that any provision of the Agreement (or part of any provision) is invalid, illegal or unenforceable, that provision or part provision shall, to the extent required, be deemed deleted, and the validity and enforceability of the other provisions of the Agreement shall not be affected.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">15.6</strong> Third Parties. Save as expressly provided in this Agreement, a person who is not a party to the Agreement shall have no rights to enforce any of its terms.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">15.7</strong> Force Majeure. A Force Majeure Event means an event beyond the reasonable control of either Party, including but not limited to strikes, lock-outs or other industrial disputes, act of God, war, riot, civil commotion, malicious damage, compliance with any law or governmental order, accident, breakdown of plant or machinery, fire, flood, storm or default of suppliers or subcontractors. Neither Party shall be liable to the other as a result of any delay or failure to perform its obligations under the Agreement as a result of a Force Majeure Event. If the Force Majeure Event continues for a period of 14 days or more, either Party shall, without limiting its other rights or remedies, have the right to terminate the Agreement immediately by giving written notice to the other Party.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">16. Governing Law and Jurisdiction</h2>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">16.1</strong> The Agreement and any dispute or claim arising out of or in connection with it shall be governed by and construed in accordance with the laws of the United Arab Emirates, and any and all such disputes shall be referred to the exclusive jurisdiction of the Courts of Dubai, U.A.E.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">16.2</strong> Notwithstanding Clause 16.1 above, the Company reserves the right at its sole discretion to commence legal proceedings against the Client in any other court of competent jurisdiction, and the commencement of such legal proceedings in one or more jurisdictions shall not preclude the commencement of legal proceedings by the Company in any other jurisdiction, whether concurrently or not.</p>
      <p className="legal-clause min-w-0 break-words pl-4 sm:pl-5"><strong className="font-semibold text-pelagic-charcoal">16.3</strong> The Client shall not commence any legal proceedings in relation to any matter arising out of or in connection with the Agreement in any jurisdiction other than the Courts of Dubai, U.A.E.</p>
      <h2 className="min-w-0 break-words pt-2 text-pelagic-ink">Contact Us</h2>
      <p className="min-w-0 break-words">If You have any questions regarding this page, You can contact Us:</p>
      <ul className={legalContactListClassName}>
        <LegalContactListItem kind="mail">
          <a href="mailto:info@pelagic-marine.com" className="break-all">
            info@pelagic-marine.com
          </a>
        </LegalContactListItem>
        <LegalContactListItem kind="phone">+971 50 394 1049</LegalContactListItem>
        <LegalContactListItem kind="location">
          Office No. 104, Almas Business Center, Aghaadir Building, Al Raffa, Dubai, U.A.E.
        </LegalContactListItem>
      </ul>
    </div>
  );
}
