import type { Metadata } from "next";
import Link from "next/link";
import { LegalPageShell } from "@/components/legal/LegalPageShell";
import {
  LegalContactListItem,
  legalContactListClassName,
} from "@/components/legal/LegalContactIcons";
import { company } from "@/lib/site-data";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Pelagic Marine Solutions LLC collects, uses, stores, shares and protects personal data when you use our website and services.",
};

const wrap = "min-w-0 break-words";

export default function PrivacyPage() {
  return (
    <LegalPageShell title="Privacy policy">
      <div className={wrap}>
        <p className={wrap}>
          This Privacy Policy describes how Pelagic Marine Solutions LLC (“Pelagic”, the “Company”,
          “We”, “Us” or “Our”) sets out Our policies and procedures on the collection, use, storage,
          sharing and protection, and disclosure of Your Personal Data when You visit Our Website or
          use Our Services, communicate with Us, or otherwise interact with Us in connection with Our
          Services. We are committed to protecting Your privacy and processing Personal Data in
          accordance with applicable data protection laws.
        </p>
        <p className={wrap}>
          This Privacy Policy also explains Your privacy rights in relation to Your Personal Data and
          how the law protects You. You may exercise those rights as described below. We use Your
          personal data to provide and improve the Service. Your Personal Data will be collected and
          processed in accordance with this Privacy Policy and applicable law. By using the Service,
          You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 className={wrap}>Interpretation and Definitions</h2>
        <dl className={`${wrap} space-y-3`}>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Company”</dt>
          <dd className={`${wrap} pb-2`}>
            means Pelagic Marine Solutions L.L.C. (referred to as “Pelagic”, “the Company”, “We”,
            “Us” or “Our”), having its office at: Office No. 104, Almas Business Center, Aghaadir
            Building, Al Raffa, Dubai, U.A.E.
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Cookies”</dt>
          <dd className={`${wrap} pb-2`}>
            means small files that are placed on Your computer, mobile device or any other device by
            a website, containing information relating to Your use of that website, including the
            details of Your browsing history on that website among its many uses, Your browsing
            activity and Your preferences.
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Device”</dt>
          <dd className={`${wrap} pb-2`}>
            means any device that can access the Service, such as a computer, a mobile phone or a
            digital tablet.
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Personal Data”</dt>
          <dd className={`${wrap} pb-2`}>
            means any information that relates to an identified or identifiable individual directly or
            indirectly, including, where applicable, names, contact details, identification details
            and other information capable of identifying an individual, in accordance with applicable
            data protection laws.
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Service”</dt>
          <dd className={`${wrap} pb-2`}>
            means the Website and the Website-related services and functions provided by Pelagic.
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Service Provider”</dt>
          <dd className={`${wrap} pb-2`}>
            means any natural or legal person who processes the Personal Data on behalf of the
            Company — third-party companies or individuals engaged by the Company to facilitate the
            Service, to provide the Service on behalf of the Company, to perform services related to
            the Service, or to assist the Company in analysing how the Service is used.
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Usage Data”</dt>
          <dd className={`${wrap} pb-2`}>
            means Personal Data collected automatically, either generated by the use of the Service or
            from the Service infrastructure itself (for example, the duration of a page visit).
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“Website”</dt>
          <dd className={`${wrap} pb-2`}>
            means the website operated by Pelagic Marine Solutions LLC, accessible from{" "}
            <a href="https://pelagic-marine.com" className="break-all">
              https://pelagic-marine.com
            </a>
          </dd>
          <dt className={`${wrap} font-semibold text-pelagic-charcoal`}>“You”</dt>
          <dd className={`${wrap} pb-2`}>
            means the individual accessing or using the Service, or the company or other legal entity
            on behalf of which such individual is accessing or using the Service.
          </dd>
        </dl>

        <h2 className={wrap}>Scope and Governing Data-Protection Law</h2>
        <p className={wrap}>
          The Company is established in Dubai, United Arab Emirates, and serves clients globally. We
          process Personal Data in accordance with U.A.E. Federal Decree-Law No. 45 of 2021 on the
          Protection of Personal Data as amended from time to time (the “PDPL”) together with other
          applicable U.A.E. laws and regulations relating to privacy and the protection of Personal
          Data.
        </p>
        <p className={wrap}>
          Where We collect or process Personal Data of individuals located in the European Economic
          Area or the United Kingdom in circumstances where the EU General Data Protection
          Regulation (“GDPR”) or the UK GDPR applies, We will do so in accordance with the applicable
          requirements of the GDPR and the UK GDPR, to the extent applicable to such processing.
          Where other national data-protection laws apply to the processing of Your Personal Data, We
          will comply with their mandatory requirements.
        </p>
        <p className={wrap}>
          This Privacy Policy principally applies to Personal Data collected through the Website, in
          connection with Our Services and through enquiries, communications and interactions with
          Pelagic. Where Pelagic is engaged to provide professional services, additional contractual,
          confidentiality or other data-protection obligations may apply.
        </p>

        <h2 className={wrap}>Types of Data Collected</h2>
        <h3 className={wrap}>Personal Data</h3>
        <p className={wrap}>
          While using Our Service, We may ask You to provide Us with certain personally identifiable
          information that can be used to contact or identify You — for example, when You complete an
          enquiry or contact form. This may include Your email address, first and last name, phone
          number, company name, job title or designation and the contents of Your message, together
          with Usage Data.
        </p>
        <p className={wrap}>
          Where You make an enquiry regarding Our professional services, You may also provide Personal
          Data contained in documents, correspondence or other information relating to a vessel,
          project, transaction, inspection, survey, engineering matter, legal matter or other
          professional engagement. You should only provide Personal Data that is reasonably necessary
          for Your enquiry and that You are authorised or otherwise lawfully permitted to provide to
          Us.
        </p>
        <h3 className={wrap}>Usage Data</h3>
        <p className={wrap}>
          Usage Data is collected automatically when using the Service. It may include Personal Data
          and other information such as Your device’s Internet Protocol (IP) address, browser type
          and version, the pages of the Service that You visit, the time and date of Your visit, the
          time spent on those pages, and other diagnostic data. When You access the Service by or
          through a mobile device, We may collect certain information automatically, including the
          type of device, its unique identifiers, its IP address, and Your mobile operating system
          and browser type.
        </p>

        <h2 className={wrap}>Tracking Technologies and Cookies</h2>
        <p className={wrap}>
          We use Cookies and similar tracking technologies to operate and secure the Service and to
          remember Your preferences. We use Necessary/Essential Cookies and Functionality Cookies, as
          described in Our{" "}
          <Link href="/cookies" className="break-words">
            Cookies policy
          </Link>
          .
        </p>
        <p className={wrap}>
          The Website does not currently use third-party analytics cookies (such as Google Analytics);
          should this change, We will update this Privacy Policy and the Cookies Policy and, where
          required by applicable law, obtain Your consent before placing or activating any such
          non-essential cookies or technology. You can instruct Your browser to refuse Cookies or to
          indicate when a Cookie is being sent. However, if You refuse or disable certain Cookies,
          some features or parts of the Website may not function properly.
        </p>

        <h2 className={wrap}>Use of Your Personal Data</h2>
        <p className={wrap}>The Company may use Personal Data for the following purposes:</p>
        <ul className={`${wrap} list-disc pl-5`}>
          <li className={wrap}>To provide and maintain Our Service, including to monitor its usage.</li>
          <li className={wrap}>
            To manage and respond to Your enquiries and requests submitted through the Service.
          </li>
          <li className={wrap}>
            To contact You by email, telephone or other equivalent forms of electronic communication
            regarding Your enquiry or Our services.
          </li>
          <li className={wrap}>
            To assess and respond to enquiries relating to Our naval architecture and design,
            engineering, inspection, audit, surveying, legal consultancy and other professional
            services.
          </li>
          <li className={wrap}>
            To manage Our relationship with You or the organisation You represent and, where
            applicable, to take steps in connection with a prospective or existing professional
            engagement.
          </li>
          <li className={wrap}>
            To provide You, where You have requested it or where permitted by law, with information
            about the Company’s services that are similar to those You have enquired about, unless You
            have opted out.
          </li>
          <li className={wrap}>
            For business transfers — to evaluate or conduct a merger, reorganisation, or sale or
            transfer of some or all of Our assets, in which Personal Data held by Us may be among the
            assets transferred.
          </li>
          <li className={wrap}>
            For other purposes, such as data analysis, identifying usage trends, and evaluating and
            improving Our Service and Your experience, where applicable.
          </li>
          <li className={wrap}>
            To comply with applicable legal and regulatory obligations and lawful requests from
            courts, government authorities or other competent authorities.
          </li>
          <li className={wrap}>
            To establish, exercise or defend legal rights or claims and to protect the rights,
            property and legitimate interests of Pelagic, Our clients and other relevant parties.
          </li>
          <li className={wrap}>
            To protect the security and integrity of Our Website, systems and information and to
            prevent, detect or investigate fraud, misuse, security incidents or other unlawful
            activity.
          </li>
        </ul>

        <h2 className={wrap}>Legal Bases for Processing</h2>
        <p className={wrap}>
          We process Personal Data with Your consent or where the processing is otherwise permitted
          under the PDPL or other applicable law. This may include processing that is necessary in
          connection with the performance of a contract or action taken in connection with a
          prospective contractual relationship, compliance with applicable legal obligations, the
          establishment, exercise or defence of legal claims, or another lawful ground recognised
          under applicable law.
        </p>
        <p className={wrap}>
          Where We rely on Your consent to process Personal Data, You may withdraw Your consent at
          any time, subject to applicable law. Withdrawal of consent will not affect the lawfulness of
          processing carried out before such withdrawal.
        </p>
        <p className={wrap}>
          Where the GDPR or UK GDPR applies, We rely on the following legal bases: Your consent (which
          You may withdraw at any time); the performance of a contract or steps taken at Your request
          prior to entering into a contract; compliance with a legal obligation; and Our legitimate
          interests in operating, securing and promoting Our business, provided these are not
          overridden by Your rights and interests. Where the PDPL or another applicable law governs,
          We process personal data on the corresponding lawful bases recognised under that law.
        </p>

        <h2 className={wrap}>Sharing of Your Personal Data</h2>
        <p className={wrap}>
          We may share Your Personal Data with Service Providers to monitor and analyse the use of
          Our Service and to contact You; in connection with a business transfer; with Our
          professional advisers; or with Your consent.
        </p>
        <p className={wrap}>
          Where reasonably required in connection with Our business or the provision of Our Services,
          and subject to applicable law, We may also share Personal Data with Our employees,
          consultants, contractors, technical advisers, surveyors, engineers and other persons
          involved in providing or supporting the relevant services.
        </p>
        <p className={wrap}>
          We may also disclose Your Personal Data where required to do so by law or in response to
          valid requests by public authorities, courts, or other competent governmental authorities.
        </p>
        <p className={wrap}>We do not sell or rent Your Personal Data.</p>
        <p className={wrap}>
          Where a Service Provider processes Personal Data on Our behalf, we will take reasonable
          steps to ensure that such Personal Data is handled in accordance with applicable
          data-protection and confidentiality requirements.
        </p>

        <h2 className={wrap}>Retention of Your Personal Data</h2>
        <p className={wrap}>
          The Company will retain Your Personal Data only for as long as is necessary for the
          purposes set out in this Privacy Policy, and to the extent necessary to comply with Our
          legal obligations, resolve disputes and enforce Our agreements and policies.
        </p>
        <p className={wrap}>
          The applicable retention period may vary depending on the nature of the Personal Data, the
          purposes for which it was collected, the nature of Our relationship with You and applicable
          legal, contractual and professional record-retention requirements.
        </p>
        <p className={wrap}>
          Usage Data is generally retained for a shorter period, except where it is used to strengthen
          the security or improve the functionality of the Service, or where We are legally obligated
          to retain it for longer.
        </p>
        <p className={wrap}>
          When Personal Data is no longer required for the purposes for which it was collected or for
          any applicable legal or legitimate retention purpose, We will take reasonable steps to
          securely delete, anonymise or otherwise dispose of it in accordance with applicable law.
        </p>

        <h2 className={wrap}>Transfer of Your Personal Data</h2>
        <p className={wrap}>
          Your information, including Personal Data, is processed at the Company’s operating offices
          and in any other places where the parties involved in the processing are located. This may
          mean Your Personal Data is transferred to, and maintained on, computers located outside of
          Your state, province or country, where data-protection laws may differ from those in Your
          jurisdiction.
        </p>
        <p className={wrap}>
          Where necessary for the provision of Our Services or business operations, Personal Data may
          be transferred to or processed in countries outside the United Arab Emirates, subject to
          applicable data protection laws.
        </p>
        <p className={wrap}>
          The Company will take all steps reasonably necessary to ensure that Your Personal Data is
          treated securely and in accordance with this Privacy Policy, including, where required,
          putting in place appropriate safeguards for international transfers and ensuring that such
          transfers are undertaken in accordance with the requirements applicable to cross-border
          transfers under the PDPL and any other applicable data protection law.
        </p>

        <h2 className={wrap}>Your Rights</h2>
        <p className={wrap}>
          Subject to applicable laws, You have the right to obtain information regarding the
          processing of Your Personal Data and to access, correct, update or request deletion of Your
          Personal Data; to object to or restrict certain processing; to request portability of Your
          Personal Data; and, where processing is based on consent, to withdraw that consent at any
          time.
        </p>
        <p className={wrap}>
          Where provided under applicable law, You may also have the right to request that certain
          processing be restricted or stopped, including the right to object to processing for
          direct-marketing purposes and rights in relation to certain automated processing and
          profiling.
        </p>
        <p className={wrap}>
          You may exercise these rights, or request access to, correction or deletion of any Personal
          Data You have provided, by contacting Us at{" "}
          <a href={`mailto:${company.emails.info}`} className="break-all">
            {company.emails.info}
          </a>
          . We may request reasonable information to verify Your identity before responding to or
          acting upon a request. Your rights may be subject to limitations or exceptions provided under
          applicable law.
        </p>
        <p className={wrap}>
          Please note that We may need to retain certain Personal Data where We have a legal obligation
          or lawful basis to do so.
        </p>
        <p className={wrap}>
          If You are in the EEA or UK and the GDPR or UK GDPR applies to the relevant processing of
          Your Personal Data, You also have the right to lodge a complaint with Your local supervisory
          authority where You believe that Your Personal Data has been processed in violation of
          applicable law.
        </p>

        <h2 className={wrap}>Security of Your Personal Data</h2>
        <p className={wrap}>
          The security of Your Personal Data is important to Us. We use commercially acceptable means
          to protect Your Personal Data including reasonable technical and organisational measures
          designed to protect Personal Data against unauthorised or unlawful access, processing,
          alteration, disclosure, loss or destruction. However, no method of transmission over the
          Internet or method of electronic storage is 100% secure, and We cannot guarantee its
          absolute security.
        </p>
        <p className={wrap}>
          Where We become aware of a Personal Data breach, We will take appropriate steps to
          investigate, contain and address the breach and make any notification required under
          applicable data-protection law.
        </p>

        <h2 className={wrap}>Children’s Privacy</h2>
        <p className={wrap}>
          Our Service does not address anyone under the age of 18, and We do not knowingly collect
          Personal Data from anyone under the age of 18. If You are a parent or guardian and You are
          aware that Your child has provided Us with Personal Data, please contact Us, and We will take
          appropriate steps to remove that information, subject to applicable law.
        </p>

        <h2 className={wrap}>Links to Other Websites</h2>
        <p className={wrap}>
          Our Service may contain links to other websites or services that are not operated by Us. We
          strongly advise You to review the privacy policies and terms of any third-party websites or
          services that You access through Our Service. We have no control over, and assume no
          responsibility for, the content, availability, security, privacy policies or practices of
          any such third-party sites or services. Your access to and use of such third-party websites
          or services is subject to their respective terms and policies.
        </p>

        <h2 className={wrap}>Confidentiality and Professional Services</h2>
        <p className={wrap}>
          Personal Data and other information provided to Pelagic in connection with an actual or
          prospective professional engagement may also be subject to contractual confidentiality
          obligations or other professional duties applicable to the relevant service. Nothing in this
          Privacy Policy limits any higher standard of confidentiality that Pelagic may be required to
          observe under an applicable contract, professional obligation or law.
        </p>
        <p className={wrap}>
          The submission of an enquiry or information through the Website does not, by itself, create
          a professional engagement or contractual relationship with Pelagic. Any professional
          engagement will be subject to Pelagic’s applicable terms of engagement or other contractual
          documentation agreed between the relevant parties.
        </p>

        <h2 className={wrap}>Changes to This Privacy Policy</h2>
        <p className={wrap}>
          We may update Our Privacy Policy from time to time. Any changes will be posted on this
          page, and You are advised to review this Privacy Policy periodically. Changes to this Privacy
          Policy are effective when they are posted on this page.
        </p>

        <h2 className={wrap}>Contact Us</h2>
        <p className={wrap}>If You have any questions regarding this page, You can contact Us:</p>
        <ul className={legalContactListClassName}>
          <LegalContactListItem kind="mail">
            <a href={`mailto:${company.emails.info}`} className="break-all">
              {company.emails.info}
            </a>
          </LegalContactListItem>
          <LegalContactListItem kind="phone">+971 50 394 1049</LegalContactListItem>
          <LegalContactListItem kind="location">
            Office No. 104, Almas Business Center, Aghaadir Building, Al Raffa, Dubai,
            U.A.E.
          </LegalContactListItem>
        </ul>
      </div>
    </LegalPageShell>
  );
}
